[
  {
    "cmd": [
      "python",
      "-u",
      "import sys; sys.exit(1)"
    ],
    "name": "Recipe failed. Reason: Fake failure",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@python.inline@import sys; sys.exit(1)@@@",
      "@@@STEP_LOG_END@python.inline@@@",
      "@@@STEP_FAILURE@@@"
    ]
  },
  {
    "failure": {
      "failure": {},
      "humanReason": "Step('Recipe failed. Reason: Fake failure') (retcode: 1)"
    },
    "name": "$result"
  }
]