[
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('Trying to take the mean of an empty list.',)"
    },
    "name": "$result"
  }
]