[
  {
    "failure": {
      "exception": {
        "traceback": [
          "<omitted by recipe engine>"
        ]
      },
      "humanReason": "Uncaught Exception: AssertionError()"
    },
    "name": "$result"
  }
]