[
  {
    "cmd": [
      "python3",
      "-u",
      "[CACHE]/builder/src/tools/mb/mb.py",
      "analyze",
      "-m",
      "fake-try-group",
      "-b",
      "fake-try-builder",
      "--config-file",
      "[CACHE]/builder/src/tools/mb/mb_config.pyl",
      "--goma-dir",
      "[CACHE]/goma/client",
      "-v",
      "//out/Release",
      "{\"additional_compile_targets\": [], \"files\": [\"foo.cc\"], \"test_targets\": [\"base_unittests\"]}",
      "/path/to/tmp/json",
      "--json-output",
      "/path/to/tmp/json"
    ],
    "cwd": "[CACHE]/builder/src",
    "env": {
      "CHROME_HEADLESS": "1"
    },
    "luci_context": {
      "realm": {
        "name": "chromium:try"
      },
      "resultdb": {
        "current_invocation": {
          "name": "invocations/build:8945511751514863184",
          "update_token": "token"
        },
        "hostname": "rdbhost"
      }
    },
    "name": "analyze",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@json.output@{@@@",
      "@@@STEP_LOG_LINE@json.output@  \"invalid_targets\": [@@@",
      "@@@STEP_LOG_LINE@json.output@    \"invalid target\", @@@",
      "@@@STEP_LOG_LINE@json.output@    \"another one\"@@@",
      "@@@STEP_LOG_LINE@json.output@  ]@@@",
      "@@@STEP_LOG_LINE@json.output@}@@@",
      "@@@STEP_LOG_END@json.output@@@",
      "@@@STEP_LOG_END@json.output[failure_summary] (invalid)@@@",
      "@@@STEP_LOG_LINE@json.output[failure_summary] (exception)@No JSON object could be decoded@@@",
      "@@@STEP_LOG_END@json.output[failure_summary] (exception)@@@"
    ]
  },
  {
    "failure": {
      "failure": {},
      "humanReason": "Error, following targets were not found: invalid target, another one"
    },
    "name": "$result"
  }
]